# Generated by Django 5.1.3 on 2024-11-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('water_level', models.FloatField()),
                ('battery_state', models.FloatField()),
            ],
            options={
                'db_table': 'sensordata',
            },
        ),
    ]
