# Generated by Django 5.1.4 on 2024-12-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('upazila', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('aez', models.CharField(max_length=255)),
                ('hotspot', models.CharField(max_length=255)),
                ('risk_area', models.CharField(max_length=255)),
                ('nid', models.CharField(max_length=20)),
                ('personal_phone', models.CharField(max_length=20)),
                ('official_phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('facebook_id', models.CharField(max_length=255)),
                ('official_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
