# Generated by Django 5.1.4 on 2024-12-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_admininformation_delete_sensordata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admininformation',
            table='AdminInformation',
        ),
    ]
