# Generated by Django 5.1.4 on 2024-12-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_potentiometerdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('water_level', models.FloatField()),
                ('require_water', models.FloatField()),
                ('rain', models.FloatField()),
                ('pump', models.BooleanField()),
                ('charge', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '1124',
            },
        ),
        migrations.CreateModel(
            name='UltraSoundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('water_level', models.FloatField()),
                ('require_water', models.FloatField()),
                ('rain', models.FloatField()),
                ('pump', models.BooleanField()),
                ('charge', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '1125',
            },
        ),
    ]
